import type { Lang, ShootRecord } from "./types";
import { score } from "./types";
import { tagLabel } from "./meta";

/** Render a saved shoot as a plain-text / Markdown "feuille de risques". */
export function toMarkdown(rec: ShootRecord): string {
  const en = rec.lang === "en";
  const b = rec.brief;
  const r = rec.report;
  const L = labels(rec.lang);

  const out: string[] = [];
  out.push(`# ${L.sheet} — ${rec.name || b.title || L.untitled}`);
  out.push("");

  // Brief block
  const env =
    b.env === "interieur"
      ? en ? "Interior" : "Intérieur"
      : b.env === "exterieur"
        ? en ? "Exterior" : "Extérieur"
        : en ? "Mixed" : "Mixte";
  const meta: [string, string][] = [
    [L.setting, env],
    [L.location, b.locationNote],
    [L.date, b.date],
    [L.call, b.callTime],
    [L.crew, b.crewSize],
    [L.gear, b.gear],
    [L.constraints, b.constraints.map((id) => tagLabel(id, rec.lang)).join(", ")],
  ];
  for (const [k, v] of meta) {
    if (v && v.trim()) out.push(`**${k}:** ${v.trim()}`);
  }
  if (b.scene.trim()) {
    out.push("");
    out.push(`> ${b.scene.trim().replace(/\n/g, "\n> ")}`);
  }
  out.push("");

  // Verdict
  if (r.verdict) {
    out.push(`## ${L.verdict}`);
    out.push(r.verdict);
    out.push("");
  }

  // Risks, sorted
  const sorted = [...r.risks].sort((a, c) => score(c) - score(a));
  out.push(`## ${L.risks} (${sorted.length})`);
  out.push("");
  for (const risk of sorted) {
    out.push(
      `### ${risk.title}  \`${risk.category}\`  ` +
        `[${L.sev} ${risk.severity} × ${L.lik} ${risk.likelihood} = ${score(risk)}]`,
    );
    if (risk.why) out.push(`*${risk.why}*`);
    if (risk.mitigations.length) {
      out.push("");
      out.push(`${L.fixes}:`);
      for (const m of risk.mitigations) out.push(`- ${m}`);
    }
    out.push("");
  }

  // Plan B
  if (r.planB) {
    out.push(`## ${L.planB}`);
    out.push(r.planB);
    out.push("");
  }

  out.push("---");
  out.push(L.footer);
  return out.join("\n");
}

function labels(lang: Lang) {
  if (lang === "en") {
    return {
      sheet: "Risk sheet",
      untitled: "Untitled shoot",
      setting: "Setting",
      location: "Location",
      date: "Date",
      call: "Call time",
      crew: "Crew/cast",
      gear: "Gear",
      constraints: "Constraints",
      verdict: "What a good 1st AD would tell you",
      risks: "Risks",
      sev: "Sev",
      lik: "Lik",
      fixes: "Fixes",
      planB: "Plan B",
      footer: "Generated by L'Imprévu — a pre-pro opinion, not a guarantee.",
    };
  }
  return {
    sheet: "Feuille de risques",
    untitled: "Tournage sans titre",
    setting: "Décor",
    location: "Lieu",
    date: "Date",
    call: "Heure d'appel",
    crew: "Équipe/cast",
    gear: "Gear",
    constraints: "Contraintes",
    verdict: "Ce qu'un bon 1er assistant te dirait",
    risks: "Risques",
    sev: "Grav",
    lik: "Prob",
    fixes: "Parades",
    planB: "Plan B",
    footer: "Généré par L'Imprévu — un avis de pré-prod, pas une garantie.",
  };
}

export function downloadMarkdown(rec: ShootRecord) {
  const md = toMarkdown(rec);
  const slug = (rec.name || rec.brief.title || "feuille-de-risques")
    .toLowerCase()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 48);
  const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${slug || "feuille"}.md`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
